services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sygmanifv2prod_app
    volumes:
      - ./app:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_app
    ports:
      - "8082:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Cbcfaso1978
      MYSQL_DATABASE: sygmanifv2prod
      MYSQL_USER: cbc
      MYSQL_PASSWORD: Cbcfaso@1978
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./db_init:/docker-entrypoint-initdb.d
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: Cbcfaso1978
    ports:
      - "8081:80"  # Accès à phpMyAdmin sur ce port
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
  
